/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DaycloseRouteImport } from './routes/dayclose'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SystemRouteImport } from './routes/system'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as WorkersRouteImport } from './routes/workers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DaycloseRoute = DaycloseRouteImport.update({
  id: '/dayclose',
  path: '/dayclose',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/checkin': typeof CheckinRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dayclose': typeof DaycloseRoute
  '/expenses': typeof ExpensesRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/packages': typeof PackagesRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/checkin': typeof CheckinRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dayclose': typeof DaycloseRoute
  '/expenses': typeof ExpensesRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/packages': typeof PackagesRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/checkin': typeof CheckinRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dayclose': typeof DaycloseRoute
  '/expenses': typeof ExpensesRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/packages': typeof PackagesRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
  '/workers': typeof WorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/checkin'
    | '/coupons'
    | '/customers'
    | '/dayclose'
    | '/expenses'
    | '/history'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/packages'
    | '/pos'
    | '/products'
    | '/queue'
    | '/reports'
    | '/sales'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/system'
    | '/users'
    | '/vehicles'
    | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/checkin'
    | '/coupons'
    | '/customers'
    | '/dayclose'
    | '/expenses'
    | '/history'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/packages'
    | '/pos'
    | '/products'
    | '/queue'
    | '/reports'
    | '/sales'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/system'
    | '/users'
    | '/vehicles'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/checkin'
    | '/coupons'
    | '/customers'
    | '/dayclose'
    | '/expenses'
    | '/history'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/packages'
    | '/pos'
    | '/products'
    | '/queue'
    | '/reports'
    | '/sales'
    | '/services'
    | '/settings'
    | '/shifts'
    | '/system'
    | '/users'
    | '/vehicles'
    | '/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  CheckinRoute: typeof CheckinRoute
  CouponsRoute: typeof CouponsRoute
  CustomersRoute: typeof CustomersRoute
  DaycloseRoute: typeof DaycloseRoute
  ExpensesRoute: typeof ExpensesRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  PackagesRoute: typeof PackagesRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  QueueRoute: typeof QueueRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  ShiftsRoute: typeof ShiftsRoute
  SystemRoute: typeof SystemRoute
  UsersRoute: typeof UsersRoute
  VehiclesRoute: typeof VehiclesRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dayclose': {
      id: '/dayclose'
      path: '/dayclose'
      fullPath: '/dayclose'
      preLoaderRoute: typeof DaycloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  CheckinRoute: CheckinRoute,
  CouponsRoute: CouponsRoute,
  CustomersRoute: CustomersRoute,
  DaycloseRoute: DaycloseRoute,
  ExpensesRoute: ExpensesRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  PackagesRoute: PackagesRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  QueueRoute: QueueRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  ShiftsRoute: ShiftsRoute,
  SystemRoute: SystemRoute,
  UsersRoute: UsersRoute,
  VehiclesRoute: VehiclesRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
